services:
  server:
    user: "0:0"
    image: codejoin-s
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    image: codejoin-c
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5000
        - VITE_SUBDOMAIN=dev.codejoin.roshananand.cloud
    ports:
      - "5173:5173"
    depends_on:
      - server
  traefik:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme.json:/acme.json
    restart: always
    networks:
      - codejoin_net

networks:
  codejoin_net:
    external: true