services:
  server:
    user: "0:0"  
    image: codejoin-s:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - codejoin_net
    restart: always
    ports:
      - "5000:5000"

  client:
    image: codejoin-c:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5000
        - VITE_REDIRECT_BACKEND_URL=http://localhost:5000
    depends_on:
      - server
    ports:
      - "5173:80"
    networks:
      - codejoin_net
    restart: always

networks:
  codejoin_net:
    driver: bridge
